# Generated by Django 5.0.2 on 2025-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="available_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="budget",
            name="actual_savings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="budget",
            name="monthly_expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="budget",
            name="monthly_income",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name="budget",
            name="suggested_savings",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
