# Generated by Django 5.0.2 on 2025-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
