# Generated by Django 5.0.2 on 2025-07-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_transaction_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="external_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
