# Generated by Django 5.0.2 on 2025-05-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("CC", "Cédula de Ciudadanía"),
                    ("CE", "Cédula de Extranjería"),
                    ("NIT", "Número de Identificación Tributaria"),
                    ("PPT", "Permiso Especial de Permanencia Temporal"),
                ],
                max_length=3,
            ),
        ),
    ]
